# =============================================================================
# ðŸ” SwaggerHub Generate & Sync
# Generates and syncs Swagger/OpenAPI specs to SwaggerHub.
# Inputs:
#   - api: API name in SwaggerHub
#   - owner: SwaggerHub owner
#   - version: API version
#   - file: Path to OpenAPI spec file
# =============================================================================

name: SwaggerHub Generate and Sync
run-name: >-
  ${{
  format('Swagger Hub sync `{0}`', 
      github.event.inputs.runner || vars.DEFAULT_RUNNER
      )
  }}

on:
  workflow_call:
    secrets:
      API_KEY:
        required: true
    inputs:
      runner:
        description: 'Choose the runner'
        required: false
        default: 'ubuntu-latest'
        type: string
      owner:
        description: 'Set the swagger hub project owner'
        required: true
        type: string
      api_name:
        description: 'Set the API name'
        required: true
        type: string
      release_version:
        description: 'Set the release version or tag name'
        required: true
        type: string

jobs:
  generate_and_sync:
    name: Generate and Sync Swagger
    runs-on: ${{ inputs.runner }}
    container: 'node:22.14'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install swagger-cli
        run: npm i -g swagger-cli

      - name: Generate Swagger file
        run: npm run swagger-generate

      - name: Verify Swagger file
        run: |
          if [ ! -f swagger.yaml ]; then
            echo "swagger.yaml not found!"
            exit 1
          fi

      - name: Sync with SwaggerHub
        run: |
          curl -X POST "https://api.swaggerhub.com/apis/${{ inputs.owner }}/${{ inputs.api_name }}?version=${{ inputs.release_version }}&isPrivate=true" \
          -H "Authorization: Bearer ${{ secrets.API_KEY }}" \
          -H "Content-Type: application/yaml" \
          --data-binary @swagger.yaml
